spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datingdb
    username: root
    password: lahoud123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

